
eureka:
  instance:
    hostname: localhost #Host where eureka server is running. To change depends on environment.

  client:
    register-with-eureka: false #By default is true.  Eureka don't need to register itself
    fetch-registry: false #By default is true. Eureka don't need to fetch anything.
    service-url: #Map of urls to communicate with eureka server. ex: https://ec2-256-156-243-129.compute-1.amazonaws.com:7001/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 8761

spring:
  config:
    import: optional:configserver:http://localhost:8888 #Without spaces. If this application doesn't find config from config server it will not fail
  application:
    name: discovery